-- MySQL Script generated by MySQL Workbench
-- Sat Dec 12 10:42:08 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema carlive
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carlive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carlive` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `carlive` ;

-- -----------------------------------------------------
-- Table `carlive`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`perfil` (
  `perfil_id` INT NOT NULL AUTO_INCREMENT,
  `perfil_nome` VARCHAR(45) NOT NULL,
  `perfil_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`perfil_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`estado` (
  `estado_id` INT NOT NULL AUTO_INCREMENT,
  `estado_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`cidade` (
  `cidade_id` INT NOT NULL AUTO_INCREMENT,
  `cidade_nome` VARCHAR(100) NOT NULL,
  `cidade_estado_id` INT NOT NULL,
  PRIMARY KEY (`cidade_id`),
  INDEX `fk_city_state_idx` (`cidade_estado_id` ASC),
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`cidade_estado_id`)
    REFERENCES `carlive`.`estado` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`empresa` (
  `empresa_id` INT NOT NULL AUTO_INCREMENT,
  `empresa_nome` VARCHAR(45) NOT NULL,
  `empresa_logradouro` VARCHAR(120) NOT NULL,
  `empresa_numero` VARCHAR(5) NULL,
  `empresa_complemento` VARCHAR(15) NULL,
  `empresa_cidade_id` INT NOT NULL,
  `empresa_cep` VARCHAR(45) NOT NULL,
  `empresa_telefone` VARCHAR(45) NULL,
  `empresa_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `empresa_usuario_id_ativacao` INT NOT NULL,
  `empresa_data_ativacao` DATETIME NOT NULL,
  `empresa_usuario_id_desativacao` INT NULL,
  `empresa_data_desativacao` DATETIME NULL,
  PRIMARY KEY (`empresa_id`),
  INDEX `empresa_cidade_idx` (`empresa_cidade_id` ASC),
  INDEX `fk_empresa_usuario_ativacao_idx` (`empresa_usuario_id_ativacao` ASC),
  INDEX `fk_empresa_usuario_desativacao_idx` (`empresa_usuario_id_desativacao` ASC),
  CONSTRAINT `fk_empresa_cidade`
    FOREIGN KEY (`empresa_cidade_id`)
    REFERENCES `carlive`.`cidade` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_usuario_ativacao`
    FOREIGN KEY (`empresa_usuario_id_ativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_usuario_desativacao`
    FOREIGN KEY (`empresa_usuario_id_desativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(100) NOT NULL,
  `usuario_cpf` VARCHAR(50) NOT NULL,
  `usuario_password` VARCHAR(50) NOT NULL,
  `usuario_telefone1` VARCHAR(45) NULL,
  `usuario_telefone2` VARCHAR(45) NULL,
  `usuario_telefone3` VARCHAR(45) NULL,
  `usuario_email` VARCHAR(45) NULL,
  `usuario_empresa_id` INT NOT NULL,
  `usuario_perfil_id` INT NOT NULL,
  `usuario_sin_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `usuario_data_ativacao` DATETIME NOT NULL,
  `usuario_usuario_id_ativacao` INT NOT NULL,
  `usuario_data_desativacao` DATETIME NULL,
  `usuario_usuario_id_desativacao` INT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_user_profile_idx` (`usuario_perfil_id` ASC),
  INDEX `fk_user_company_idx` (`usuario_empresa_id` ASC),
  INDEX `fk_usuario_usuario_ativacao_idx` (`usuario_id` ASC, `usuario_usuario_id_ativacao` ASC),
  INDEX `fk_usuario_usuario_desativacao_idx` (`usuario_usuario_id_desativacao` ASC),
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`usuario_perfil_id`)
    REFERENCES `carlive`.`perfil` (`perfil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_empresa`
    FOREIGN KEY (`usuario_empresa_id`)
    REFERENCES `carlive`.`empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuario_ativacao`
    FOREIGN KEY (`usuario_id` , `usuario_usuario_id_ativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_empresa_id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuario_desativacao`
    FOREIGN KEY (`usuario_usuario_id_desativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`carro` (
  `carro_id` INT NOT NULL AUTO_INCREMENT,
  `carro_frota` VARCHAR(45) NOT NULL,
  `carro_placa` VARCHAR(12) NOT NULL,
  `carro_km` VARCHAR(10) NOT NULL,
  `carro_empresa_id` INT NOT NULL,
  `carro_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `carro_data_ativacao` DATETIME NOT NULL,
  `carro_usuario_id_ativacao` INT NOT NULL,
  `carro_data_desativacao` DATETIME NULL,
  `carro_usuario_desativacao` INT NULL,
  PRIMARY KEY (`carro_id`),
  INDEX `fk_truck_company_idx` (`carro_empresa_id` ASC),
  INDEX `fk_truck_user_idx` (`carro_usuario_id_ativacao` ASC),
  INDEX `fk_carro_usuario_desativacao_idx` (`carro_usuario_desativacao` ASC),
  CONSTRAINT `fk_carro_empresa`
    FOREIGN KEY (`carro_empresa_id`)
    REFERENCES `carlive`.`empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_usuario_ativacao`
    FOREIGN KEY (`carro_usuario_id_ativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_usuario_desativacao`
    FOREIGN KEY (`carro_usuario_desativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`viagem` (
  `viagem_id` INT NOT NULL AUTO_INCREMENT,
  `viagem_cidade_origem_id` INT NOT NULL,
  `viagem_cidade_destino_id` INT NOT NULL,
  `viagem_data_saida` DATE NOT NULL,
  `viagem_data_chegada` DATE NULL,
  `viagem_km_saida` INT(10) NOT NULL,
  `viagem_km_chegada` INT(10) NULL,
  `viagem_carro_id` INT NOT NULL,
  `viagem_usuario_id` INT NOT NULL,
  `viagem_valor_km` DECIMAL(10,2) NULL,
  `viagem_frete` DECIMAL(10,2) NOT NULL,
  `viagem_adiantamento` DECIMAL(10,2) NULL,
  `viagem_complemento` DECIMAL(10,2) NULL,
  `viagem_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `viagem_usuario_id_ativacao` INT NOT NULL,
  `viagem_data_ativacao` DATETIME NOT NULL,
  `viagem_usuario_id_desativacao` INT NULL,
  `viagem_data_desativacao` DATETIME NULL,
  PRIMARY KEY (`viagem_id`),
  INDEX `fk_travel_truck_idx` (`viagem_carro_id` ASC),
  INDEX `fk_travel_city_origin_idx` (`viagem_cidade_origem_id` ASC),
  INDEX `fk_travel_city_destination_idx` (`viagem_cidade_destino_id` ASC),
  INDEX `fk_travel_user_idx` (`viagem_usuario_id` ASC),
  CONSTRAINT `fk_viagem_carro`
    FOREIGN KEY (`viagem_carro_id`)
    REFERENCES `carlive`.`carro` (`carro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_cidade_origem`
    FOREIGN KEY (`viagem_cidade_origem_id`)
    REFERENCES `carlive`.`cidade` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_cidade_destino`
    FOREIGN KEY (`viagem_cidade_destino_id`)
    REFERENCES `carlive`.`cidade` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_usuario`
    FOREIGN KEY (`viagem_usuario_id`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_nome` VARCHAR(255) NOT NULL,
  `item_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `item_usuario_id_ativacao` INT NOT NULL,
  `item_data_ativacao` DATETIME NOT NULL,
  `item_usuario_id_desativacao` INT NULL,
  `item_data_desativacao` DATETIME NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_item_usuario_ativacao_idx` (`item_usuario_id_ativacao` ASC),
  INDEX `fk_item_usuario_desativacao_idx` (`item_usuario_id_desativacao` ASC),
  CONSTRAINT `fk_item_usuario_ativacao`
    FOREIGN KEY (`item_usuario_id_ativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_usuario_desativacao`
    FOREIGN KEY (`item_usuario_id_desativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`revisao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`revisao` (
  `revisao_id` INT NOT NULL AUTO_INCREMENT,
  `revisao_item_id` INT NOT NULL,
  `revisao_carro_id` INT NOT NULL,
  `revisao_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `revisao_valor` DOUBLE NOT NULL,
  `revisao_data` DATE NOT NULL,
  `revisao_usuario_id_ativacao` INT NOT NULL,
  `revisao_data_ativacao` DATE NOT NULL,
  `revisao_usuario_id_desativacao` INT NULL,
  `revisao_data_desativacao` DATE NULL,
  PRIMARY KEY (`revisao_id`),
  INDEX `fk_review_truck_idx` (`revisao_carro_id` ASC),
  INDEX `fk_review_user_idx` (`revisao_usuario_id_ativacao` ASC),
  INDEX `fk_revisao_usuario_desativacao_idx` (`revisao_usuario_id_desativacao` ASC),
  INDEX `fk_revisao_item_idx` (`revisao_item_id` ASC),
  CONSTRAINT `fk_revisao_carro`
    FOREIGN KEY (`revisao_carro_id`)
    REFERENCES `carlive`.`carro` (`carro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revisao_usuario_ativacao`
    FOREIGN KEY (`revisao_usuario_id_ativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revisao_usuario_desativacao`
    FOREIGN KEY (`revisao_usuario_id_desativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revisao_item`
    FOREIGN KEY (`revisao_item_id`)
    REFERENCES `carlive`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`abastecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`abastecimento` (
  `abastecimento_id` INT NOT NULL AUTO_INCREMENT,
  `abastecimento_nome` VARCHAR(255) NOT NULL,
  `abastecimento_valor` DECIMAL(10,2) NOT NULL,
  `abastecimento_litros` DOUBLE NOT NULL,
  `abastecimento_data` DATE NOT NULL,
  `abastecimento_carro_id` INT NOT NULL,
  `abastecimento_viagem_id` INT NOT NULL,
  `abastecimento_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `abastecimento_usuario_id_ativacao` INT NULL,
  `abastecimento_data_ativacao` DATETIME NULL,
  `abastecimento_usuario_id_desativacao` INT NULL,
  `abastecimento_data_desativacao` DATETIME NULL,
  PRIMARY KEY (`abastecimento_id`),
  INDEX `fk_abastecimento_carro_idx` (`abastecimento_carro_id` ASC),
  INDEX `fk_abastecimento_viagem_idx` (`abastecimento_viagem_id` ASC),
  INDEX `fk_abastecimento_usuario_ativacao_idx` (`abastecimento_usuario_id_ativacao` ASC),
  INDEX `fk_abastecimento_usuario_desativacao_idx` (`abastecimento_usuario_id_desativacao` ASC),
  CONSTRAINT `fk_abastecimento_carro`
    FOREIGN KEY (`abastecimento_carro_id`)
    REFERENCES `carlive`.`carro` (`carro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_abastecimento_viagem`
    FOREIGN KEY (`abastecimento_viagem_id`)
    REFERENCES `carlive`.`viagem` (`viagem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_abastecimento_usuario_ativacao`
    FOREIGN KEY (`abastecimento_usuario_id_ativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_abastecimento_usuario_desativacao`
    FOREIGN KEY (`abastecimento_usuario_id_desativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlive`.`despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlive`.`despesa` (
  `despesa_id` INT NOT NULL AUTO_INCREMENT,
  `despesa_nome` VARCHAR(120) NOT NULL,
  `despesa_valor` DOUBLE NOT NULL,
  `despesa_data` DATE NOT NULL,
  `despesa_carro_id` INT NOT NULL,
  `despesa_viagem_id` INT NOT NULL,
  `despesa_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `despesa_usuario_id_ativacao` INT NOT NULL,
  `despesa_data_ativacao` DATETIME NOT NULL,
  `despesa_usuario_id_desativacao` INT NULL,
  `despesa_data_desativacao` DATETIME NULL,
  PRIMARY KEY (`despesa_id`),
  INDEX `fk_despesa_carro_idx` (`despesa_carro_id` ASC),
  INDEX `fk_despesa_viagem_idx` (`despesa_viagem_id` ASC),
  INDEX `fk_despesa_usuario_ativacao_idx` (`despesa_usuario_id_ativacao` ASC),
  INDEX `fk_despesa_usuario_desativacao_idx` (`despesa_usuario_id_desativacao` ASC),
  CONSTRAINT `fk_despesa_carro`
    FOREIGN KEY (`despesa_carro_id`)
    REFERENCES `carlive`.`carro` (`carro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despesa_viagem`
    FOREIGN KEY (`despesa_viagem_id`)
    REFERENCES `carlive`.`viagem` (`viagem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despesa_usuario_ativacao`
    FOREIGN KEY (`despesa_usuario_id_ativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despesa_usuario_desativacao`
    FOREIGN KEY (`despesa_usuario_id_desativacao`)
    REFERENCES `carlive`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
